#!/usr/bin/env bash
# Render and push configuration to a node.
#
#   ./deploy/scripts/sync-config.sh node1
#   ./deploy/scripts/sync-config.sh --all
#
# Only small text files travel here: compose files, Caddyfile, Vault HCL,
# Prometheus config and the per-host .env. Application code never lands on a
# host — images are shipped separately by ship-image.sh.
#
# Secrets consumed from the environment (supplied by CI or your shell):
#   REDIS_PASSWORD, NETCUP_CUSTOMER_NUMBER, NETCUP_API_KEY, NETCUP_API_PASSWORD,
#   GRAFANA_ADMIN_PASSWORD

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

load_inventory
need_cmd rsync

TARGETS=""
while [ $# -gt 0 ]; do
  case "$1" in
    --all) TARGETS="$NODES"; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) TARGETS="$TARGETS $1"; shift ;;
  esac
done
[ -n "${TARGETS// /}" ] || die "usage: sync-config.sh <node>... | --all"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# render <template> <output> KEY=VALUE...
render() {
  local tpl="$1" out="$2"; shift 2
  local content; content="$(cat "$tpl")"
  local pair key value
  for pair in "$@"; do
    key="${pair%%=*}"; value="${pair#*=}"
    content="${content//@@$key@@/$value}"
  done
  printf '%s\n' "$content" >"$out"
}

for node in $TARGETS; do
  require_node "$node"
  role="$(node_role "$node")"
  wg_ip="$(node_wg_ip "$node")"
  vault_id="$(node_vault_id "$node")"

  step "Staging config for $node ($role)"
  rm -rf "${STAGE:?}"/*
  mkdir -p "$STAGE/compose" "$STAGE/config/vault/templates" "$STAGE/config/caddy" \
           "$STAGE/config/redis" "$STAGE/config/prometheus" "$STAGE/config/grafana"

  cp "$DEPLOY_DIR"/compose/*.yml "$STAGE/compose/"
  cp "$DEPLOY_DIR"/config/caddy/Caddyfile "$STAGE/config/caddy/"

  # --- Vault Raft config: peers are every other node -----------------------
  retry_join=""
  for peer in $NODES; do
    [ "$peer" = "$node" ] && continue
    retry_join="${retry_join}  retry_join {
    leader_api_addr = \"http://$(node_wg_ip "$peer"):8200\"
  }
"
  done
  render "$DEPLOY_DIR/config/vault/raft.hcl.tpl" "$STAGE/config/vault/raft.hcl" \
    "VAULT_NODE_ID=$vault_id" "NODE_WG_IP=$wg_ip" "RETRY_JOIN=${retry_join%$'\n'}"

  # The Vault Agent config is shared with the single-host stack; the agent
  # reaches its own node's Raft member through an extra_hosts entry.
  cp "$REPO_ROOT/vault/agent-config.hcl" "$STAGE/config/vault/agent-config.hcl"
  cp "$REPO_ROOT"/vault/templates/*.tpl "$STAGE/config/vault/templates/" 2>/dev/null || true

  # --- Prometheus (witness only) -------------------------------------------
  if [ "$role" = "witness" ]; then
    node_targets=""; cadvisor_targets=""; vault_targets=""
    for peer in $NODES; do
      peer_ip="$(node_wg_ip "$peer")"
      node_targets="${node_targets}      - targets: [\"$peer_ip:9100\"]
        labels: {node: \"$peer\", role: \"$(node_role "$peer")\"}
"
      cadvisor_targets="${cadvisor_targets}      - targets: [\"$peer_ip:8080\"]
        labels: {node: \"$peer\"}
"
      vault_targets="${vault_targets}      - targets: [\"$peer_ip:8200\"]
        labels: {node: \"$peer\", vault_id: \"$(node_vault_id "$peer")\"}
"
    done
    render "$DEPLOY_DIR/config/prometheus/prometheus.yml.tpl" "$STAGE/config/prometheus/prometheus.yml" \
      "NODE_EXPORTER_TARGETS=${node_targets%$'\n'}" \
      "CADVISOR_TARGETS=${cadvisor_targets%$'\n'}" \
      "VAULT_TARGETS=${vault_targets%$'\n'}"
    cp "$DEPLOY_DIR/config/prometheus/alerts.yml" "$STAGE/config/prometheus/"
    cp "$DEPLOY_DIR/config/grafana/datasources.yml" "$STAGE/config/grafana/"
  fi

  # --- per-host .env --------------------------------------------------------
  {
    printf '# Generated by sync-config.sh for %s (%s). Do not edit by hand.\n' "$node" "$role"
    printf 'NODE_NAME=%s\n' "$node"
    printf 'NODE_ROLE=%s\n' "$role"
    printf 'NODE_WG_IP=%s\n' "$wg_ip"
    printf 'VAULT_NODE_ID=%s\n' "$vault_id"
    printf 'GARDE_IMAGE=%s\n' "${GARDE_IMAGE:-garde/api}"
    printf 'UI_IMAGE=%s\n' "${UI_IMAGE:-garde/ui}"
    printf 'CADDY_IMAGE=%s\n' "${CADDY_IMAGE:-garde/caddy}"
    printf 'IMAGE_TAG=%s\n' "${IMAGE_TAG:-latest}"
    printf 'APP_NET_SUBNET=%s\n' "${APP_NET_SUBNET:-172.28.0.0/16}"
    printf 'APP_DOMAIN=%s\n' "${APP_DOMAIN:-}"
    printf 'API_DOMAIN=%s\n' "${API_DOMAIN:-}"
    printf 'ACME_EMAIL=%s\n' "${ACME_EMAIL:-}"
    printf 'REDIS_PASSWORD=%s\n' "${REDIS_PASSWORD:-}"
    printf 'NETCUP_CUSTOMER_NUMBER=%s\n' "${NETCUP_CUSTOMER_NUMBER:-}"
    printf 'NETCUP_API_KEY=%s\n' "${NETCUP_API_KEY:-}"
    printf 'NETCUP_API_PASSWORD=%s\n' "${NETCUP_API_PASSWORD:-}"
    printf 'GRAFANA_ADMIN_PASSWORD=%s\n' "${GRAFANA_ADMIN_PASSWORD:-}"
  } >"$STAGE/.env"
  chmod 600 "$STAGE/.env"

  step "Pushing config to $node"
  # --delete would remove host-owned state (vault/role-id, data/), so the sync
  # is additive and scoped to the directories this script owns.
  rsh="$(rsync_rsh "$node")"
  rsync -az -e "$rsh" --delete \
    "$STAGE/compose/" "$(ssh_target "$node"):$REMOTE_ROOT/compose/"
  rsync -az -e "$rsh" \
    "$STAGE/config/" "$(ssh_target "$node"):$REMOTE_ROOT/config/"
  rsync -az -e "$rsh" \
    "$STAGE/.env" "$(ssh_target "$node"):$REMOTE_ROOT/.env"

  on_node "$node" "chmod 600 '$REMOTE_ROOT/.env' && mkdir -p '$REMOTE_ROOT/vault' '$REMOTE_ROOT/data' '$REMOTE_ROOT/backup' '$REMOTE_ROOT/certs' '$REMOTE_ROOT/configs'"

  # --- Redis config: created once, then owned by Redis ---------------------
  if [ "$role" = "app-primary" ] || [ "$role" = "app-standby" ]; then
    : "${REDIS_PASSWORD:?REDIS_PASSWORD must be set to render redis.conf}"
    if on_node "$node" "test -f '$REMOTE_ROOT/config/redis/redis.conf'"; then
      log "redis.conf already exists on $node, leaving it alone"
      log "  (it records the current primary/replica state; failover rewrites it)"
    else
      replicaof=""
      if [ "$role" = "app-standby" ]; then
        primary_ip="$(node_wg_ip "${PRIMARY_NODE:?PRIMARY_NODE missing from inventory}")"
        replicaof="replicaof $primary_ip 6379"
      fi
      render "$DEPLOY_DIR/config/redis/redis.conf.tpl" "$STAGE/redis.conf" \
        "REDIS_PASSWORD=$REDIS_PASSWORD" "REPLICAOF=$replicaof"
      rsync -az -e "$(rsync_rsh "$node")" \
        "$STAGE/redis.conf" "$(ssh_target "$node"):$REMOTE_ROOT/config/redis/redis.conf"
      # uid 999 is the redis user in the official image, and it must be able to
      # rewrite this file during failover. The deploy user is not root, so the
      # ownership change runs in a throwaway container via the docker socket.
      on_node "$node" "docker run --rm -v '$REMOTE_ROOT/config/redis':/mnt alpine:3.19 \
        sh -c 'chown 999:999 /mnt/redis.conf && chmod 640 /mnt/redis.conf'"
      ok "rendered redis.conf on $node ($([ -n "$replicaof" ] && echo replica || echo primary))"
    fi
  fi

  ok "$node config synced"
done
